export const CHANGE_LESSONS = 'CHANGE_LESSONS';
export const CHANGE_INFOS = 'CHANGE_INFOS';
export const CHANGE_LIST_OFFSET = 'home/singers/CHANGE_LIST_OFFSET';
export const CHANGE_ENTER_LOADING = 'CHANGE_ENTER_LOADING';
export const CHANGE_PULLUP_LOADING = 'home/singers/PULLUP_LOADING';
export const CHANGE_PULLDOWN_LOADING = 'home/singers/PULLDOWN_LOADING';